export const products = [
  {
    id: "1",
    name: "Luxury Yacht",
    category: "boat",
    description: "A premium luxury yacht for ocean adventures",
    price: 1250000,
    image: "/Car.jpg",
  },
  {
    id: "2",
    name: "Speed Boat",
    category: "boat",
    description: "High-speed boat for water sports enthusiasts",
    price: 85000,
    image: "/car.png",
  },
  {
    id: "3",
    name: "Mountain Bike",
    category: "bike",
    description: "Professional mountain bike for rough terrains",
    price: 3500,
    image: "/Car.jpg",
  },
  {
    id: "4",
    name: "Racing Bike",
    category: "bike",
    description: "Lightweight racing bike for competitions",
    price: 5200,
    image: "/car.png",
  },
  {
    id: "5",
    name: "Luxury Sedan",
    category: "car",
    description: "Comfortable luxury sedan with premium features",
    price: 75000,
    image: "/Car.jpg",
  },
  {
    id: "6",
    name: "Sports Car",
    category: "car",
    description: "High-performance sports car with sleek design",
    price: 120000,
    image: "/car.png",
  },
  {
    id: "7",
    name: "Private Jet",
    category: "airplane",
    description: "Luxurious private jet for exclusive travel",
    price: 8500000,
    image: "/Car.jpg",
  },
  {
    id: "8",
    name: "Light Aircraft",
    category: "airplane",
    description: "Small aircraft for personal flying",
    price: 350000,
    image: "/car.png",
  },
  {
    id: "9",
    name: "Electric Car",
    category: "car",
    description: "Eco-friendly electric car with modern features",
    price: 45000,
    image: "/Car.jpg",
  },
  {
    id: "10",
    name: "Cruiser Bike",
    category: "bike",
    description: "Comfortable cruiser bike for casual riding",
    price: 1200,
    image: "/car.png",
  },
  {
    id: "11",
    name: "Fishing Boat",
    category: "boat",
    description: "Stable fishing boat with all necessary equipment",
    price: 45000,
    image: "/Car.jpg",
  },
  {
    id: "12",
    name: "Hybrid Bike",
    category: "bike",
    description: "Versatile bike for both city and light trail use",
    price: 1800,
    image: "/car.png",
  },
  {
    id: "13",
    name: "SUV",
    category: "car",
    description: "Spacious SUV with off-road capabilities",
    price: 65000,
    image: "/Car.jpg",
  },
  {
    id: "14",
    name: "Commercial Airliner",
    category: "airplane",
    description: "Large passenger aircraft for airlines",
    price: 120000000,
    image: "/car.png",
  },
  {
    id: "15",
    name: "Jet Ski",
    category: "boat",
    description: "Personal watercraft for thrilling rides",
    price: 15000,
    image: "/Car.jpg",
  },
  {
    id: "16",
    name: "Folding Bike",
    category: "bike",
    description: "Compact bike perfect for urban commuters",
    price: 950,
    image: "/car.png",
  },
  {
    id: "17",
    name: "Vintage Car",
    category: "car",
    description: "Classic vintage car in excellent condition",
    price: 250000,
    image: "/Car.jpg",
  },
  {
    id: "18",
    name: "Cargo Plane",
    category: "airplane",
    description: "Heavy-lift aircraft for freight transport",
    price: 75000000,
    image: "/car.png",
  },
  {
    id: "19",
    name: "Houseboat",
    category: "boat",
    description: "Floating home with all modern amenities",
    price: 350000,
    image: "/Car.jpg",
  },
  {
    id: "20",
    name: "Kids Bike",
    category: "bike",
    description: "Safe and durable bike for children",
    price: 350,
    image: "/car.png",
  },
];